require_relative '../../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAuthentication', :path => '../../../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorFirebaseFirestore', :path => '../../../../node_modules/@capacitor-firebase/firestore'
  pod 'CapacitorFirebaseFunctions', :path => '../../../../node_modules/@capacitor-firebase/functions'
  pod 'CapacitorFirebaseStorage', :path => '../../../../node_modules/@capacitor-firebase/storage'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorFirebaseAppCheck', :path => '../../../../node_modules/@capacitor-firebase/app-check'
  pod 'CapacitorGeolocation', :path => '../../../../node_modules/@capacitor/geolocation'
  pod 'CapacitorCamera', :path => '../../../../node_modules/@capacitor/camera'
  pod 'CapacitorAppLauncher', :path => '../../../../node_modules/@capacitor/app-launcher'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorSplashScreen', :path => '../../../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorFirebaseCrashlytics', :path => '../../../../node_modules/@capacitor-firebase/crashlytics'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/@capacitor/preferences'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/@capacitor/status-bar'
  pod 'CapacitorApp', :path => '../../../../node_modules/@capacitor/app'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorFirebaseMessaging', :path => '../../../../node_modules/@capacitor-firebase/messaging'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../../../node_modules/@capawesome/capacitor-file-picker'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
  pod 'CapacitorNetwork', :path => '../../../../node_modules/@capacitor/network'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'CapacitorFirebaseAuthentication/Google', :path => '../../../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../../../node_modules/@capacitor-firebase/analytics'
  pod 'FirebaseMessaging'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
