name: "Create release branch"
description: "Creates a release branch"

inputs:
  branch_name:
    description: "Name of the branch to create"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Git user
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create release branch
      shell: bash
      run: |
        # Fetch latest main branch
        git checkout develop
        git pull origin develop

        git checkout -b ${{ inputs.branch_name }}
        git status # Verify the branch creation
