/**
 * Daily launch-analytics digest.
 *
 * Computes each dashboard tile for the current window and the previous window
 * of the same length, reports the delta, and raises threshold alerts from
 * `dashboard.config.mjs`. Output is Markdown (default) or JSON (`--json`),
 * suitable for posting to a GitHub issue from CI (see the analytics-digest
 * workflow).
 *
 * Usage:
 *   node tools/analytics/digest.mjs [--days=7] [--json] [--dry-run]
 *
 * Env (auto-loaded from tools/analytics/.env if present):
 *   GA4_PROPERTY_ID, GOOGLE_APPLICATION_CREDENTIALS  (see README.md)
 */

import {
  buildRequest,
  consoleTiles,
  createClient,
  currentWindow,
  fail,
  loadEnv,
  previousWindow,
  queryableTiles,
  resolvePropertyId,
  runValue,
} from './ga4.mjs';

loadEnv();

const USAGE = `Daily launch-analytics digest

Usage:
  node tools/analytics/digest.mjs [--days=7] [--json] [--dry-run]

Options:
  --days=<n>   Window length in days for the current and previous periods (default 7).
  --json       Emit JSON instead of Markdown.
  --dry-run    Show the windows and thresholds without calling the API.
  --help       Show this help.`;

function parseArgs(argv) {
  const args = { days: 7, json: false, dryRun: false, help: false };
  for (const raw of argv) {
    if (raw === '--help' || raw === '-h') args.help = true;
    else if (raw === '--json') args.json = true;
    else if (raw === '--dry-run') args.dryRun = true;
    else if (raw.startsWith('--days=')) {
      const n = Number.parseInt(raw.slice('--days='.length), 10);
      if (!Number.isInteger(n) || n < 1) {
        fail(`--days must be a positive integer, got "${raw.slice(7)}".`);
      }
      args.days = n;
    } else {
      fail(`Unknown argument "${raw}". Try --help.`);
    }
  }
  return args;
}

function evaluateAlerts(tile, now, prev) {
  const alerts = [];
  const expect = tile.expect;
  if (!expect) return alerts;

  if (typeof expect.min === 'number' && now < expect.min) {
    alerts.push(`${tile.title}: ${now} in window (expected ≥ ${expect.min}).`);
  }
  if (typeof expect.maxDropPct === 'number' && prev > 0) {
    const dropPct = ((prev - now) / prev) * 100;
    if (dropPct > expect.maxDropPct) {
      alerts.push(
        `${tile.title}: down ${dropPct.toFixed(0)}% vs previous window ` +
          `(${prev} → ${now}, threshold ${expect.maxDropPct}%).`,
      );
    }
  }
  return alerts;
}

function formatDelta(now, prev) {
  const diff = now - prev;
  if (diff === 0) return '–';
  const sign = diff > 0 ? '+' : '';
  if (prev > 0) {
    const pct = Math.round((diff / prev) * 100);
    return `${sign}${diff} (${sign}${pct}%)`;
  }
  return `${sign}${diff}`;
}

function toMarkdown({ date, days, propertyId, rows, alerts }) {
  const lines = [];
  lines.push(`## Launch analytics digest — ${date}`);
  lines.push('');
  lines.push(
    `Window: last ${days} days vs previous ${days} days · property \`${propertyId}\``,
  );
  lines.push('');
  lines.push('| Metric | Category | Now | Prev | Δ |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const r of rows) {
    lines.push(
      `| ${r.title} | ${r.category} | ${r.now} | ${r.prev} | ${r.delta} |`,
    );
  }
  lines.push('');
  if (alerts.length > 0) {
    lines.push('### ⚠️ Alerts');
    for (const a of alerts) lines.push(`- ${a}`);
  } else {
    lines.push('### ✅ No threshold alerts');
  }
  lines.push('');
  const manual = consoleTiles();
  if (manual.length > 0) {
    lines.push(
      'Console-only (check manually): ' +
        manual.map((t) => `${t.title} (${t.source})`).join('; ') +
        '.',
    );
    lines.push('');
  }
  lines.push('<sub>Generated by tools/analytics/digest.mjs</sub>');
  return lines.join('\n');
}

function runDryRun({ days }) {
  const propertyId = process.env.GA4_PROPERTY_ID || '<GA4_PROPERTY_ID>';
  console.log(`DRY RUN — daily digest plan (property ${propertyId})\n`);
  console.log(`Current window:  ${JSON.stringify(currentWindow(days))}`);
  console.log(`Previous window: ${JSON.stringify(previousWindow(days))}\n`);
  console.log('Tiles + thresholds:');
  for (const tile of queryableTiles()) {
    const expect = tile.expect ? JSON.stringify(tile.expect) : 'no thresholds';
    console.log(`- ${tile.id} — ${tile.title} → ${expect}`);
  }
}

async function runLive({ days, json }) {
  const propertyId = resolvePropertyId();
  const client = await createClient();

  const rows = [];
  const alerts = [];
  for (const tile of queryableTiles()) {
    const now = await runValue(
      client,
      buildRequest(tile, propertyId, currentWindow(days)),
    );
    const prev = await runValue(
      client,
      buildRequest(tile, propertyId, previousWindow(days)),
    );
    rows.push({
      id: tile.id,
      title: tile.title,
      category: tile.category,
      now,
      prev,
      delta: formatDelta(now, prev),
    });
    alerts.push(...evaluateAlerts(tile, now, prev));
  }

  const date = new Date().toISOString().slice(0, 10);
  const payload = { date, days, propertyId, rows, alerts };

  if (json) {
    console.log(
      JSON.stringify({ ...payload, manual: consoleTiles() }, null, 2),
    );
    return;
  }
  console.log(toMarkdown(payload));
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(USAGE);
    return;
  }
  if (args.dryRun) {
    runDryRun(args);
    return;
  }
  await runLive(args);
}

main().catch((error) => fail(String(error?.message ?? error)));
