export { addNecessaryIcons } from './lib/add-necessary-icons';
export * from './lib/get-ionic-config';
export { Environment } from './lib/environment';
export * from './lib/consts';
export { getMetaReducers } from './lib/get-meta-reducers';
export { STORE_SERVICE, StoreService } from './lib/store.service';
export { APP_TITLE, APP_ICON } from './lib/app-tokens';
export { toDate } from './lib/to-date';
export { byDate } from './lib/by-date';
export { Login } from './lib/login';
export { splitTags } from './lib/split-tags';
