import type {
  FloorPlanPoint,
  FloorPlanRotation,
  FloorPlanSize,
  Millimetres,
} from './floor-plan';

/** The fields every table carries, whatever shape it is drawn as. */
interface RestaurantTableBase {
  /** Internal identifier, stable for the table's lifetime. */
  id: string;
  /**
   * Public table number or name shown to staff and guests.
   *
   * Unique within the restaurant across all rooms, because staff say
   * "table 12" without naming a room. The editor refuses a duplicate as it is
   * typed, and the publish validation of issue #1088 refuses a plan that
   * reached that state some other way - a second device, or a room that was
   * made smaller. Security rules cannot query, so no rule can hold this.
   */
  label: string;
  /**
   * The room the table stands in.
   *
   * A table can move to another room and keep its `id`, its `label` and its
   * `qrTokenId`, so printed codes stay valid.
   */
  roomId: string;
  /** Centre of the table, in room millimetres. */
  position: FloorPlanPoint;
  rotation: FloorPlanRotation;
  /**
   * Seating capacity, at least one.
   *
   * A number rather than a count of chair objects: the chairs in the plan are
   * geometry that helps staff recognise the room, and a banquette seating four
   * is one shape. Capacity is a fact about the table, not about the drawing.
   */
  seats: number;
  /**
   * Whether the table is in service at all.
   *
   * A configuration decision by the owner, not the operational "blocked right
   * now" of the live view. A disabled table stays in the plan and is not
   * orderable.
   */
  enabled: boolean;
  /**
   * The active opaque QR token, absent until the plan has been published.
   *
   * Every enabled table ends up with exactly one, generated by issue #1086 and
   * asked for by the publish step of issue #1088 and by the printable sheet of
   * issue #1087 - issuing is idempotent, so neither invalidates what the other
   * printed. The token never encodes the label, so a table number cannot be
   * guessed into a scan.
   */
  qrTokenId?: string;
}

/** A rectangular or square table, sized before rotation. */
export interface RectangularTable extends RestaurantTableBase {
  shape: 'rectangle';
  size: FloorPlanSize;
}

/**
 * A round table.
 *
 * A diameter rather than a `size`, because a round table has no width and
 * height to disagree about and the type should not permit an ellipse the
 * renderer would have to invent a rule for. `rotation` is still present and
 * still meaningful once the table carries a label or a banquette side.
 */
export interface RoundTable extends RestaurantTableBase {
  shape: 'round';
  diameter: Millimetres;
}

/**
 * A seating place in a restaurant, as a business entity rather than a shape.
 *
 * `RestaurantTable` and not `Table`, because `Table` is taken by the DOM lib
 * in every consumer of this library, and because the domain word alone says
 * nothing about which product it belongs to.
 *
 * Discriminated on `shape`, so a round table cannot carry a width and height
 * and a rectangular one cannot carry a diameter.
 *
 * The geometry fields use the coordinate system documented in
 * `floor-plan.ts`: room-relative integer millimetres, origin top-left, and a
 * `position` that is the centre of the table. The product rules are in
 * `ssot/pages/Table.md`.
 *
 * Live state is deliberately absent. A table is configuration, written by the
 * owner while editing the plan; whether a party is sitting at it right now is
 * operational and is stored separately, so staff activity never rewrites the
 * layout and rearranging the layout never disturbs a service.
 */
export type RestaurantTable = RectangularTable | RoundTable;

/** The shape a table is drawn as. */
export type TableShape = RestaurantTable['shape'];
