import { deleteApp, getApps, initializeApp } from 'firebase-admin/app';
import {
  DocumentData,
  DocumentReference,
  getFirestore,
} from 'firebase-admin/firestore';
import {
  DURABLE_IP_LIMIT_PER_WINDOW,
  DURABLE_RATE_LIMIT_WINDOW_MS,
  DURABLE_TOKEN_LIMIT_PER_WINDOW,
  SCAN_RATE_LIMITS_COLLECTION,
  bucketOf,
  resetDurableScanRateLimit,
  windowStartOf,
} from '../../shared/utils/durable-scan-rate-limit';
import { resetScanRateLimit } from '../../shared/utils/scan-rate-limit';
import {
  DismissScanAnomalyResult,
  dismissScanAnomalyHandler,
} from '../dismiss-scan-anomaly';
import { resolveTableQrTokenHandler } from '../resolve-table-qr-token';
import {
  MIN_SESSIONS_BEFORE_ANOMALY,
  SCAN_ANOMALIES_COLLECTION,
  ScanAnomalyKind,
  scanAnomalyId,
} from '../scan-anomaly';
import {
  StartTableSessionResult,
  startTableSessionHandler,
} from '../start-table-session';
import { TABLE_TOKENS_COLLECTION } from '../table-qr-tokens';
import {
  RotateTableQrTokensResult,
  rotateTableQrTokensHandler,
} from '../table-qr-tokens';
import { TableScanResult } from '../table-scan';
import { tableSessionId } from '../table-session';
import { transitionTableStateHandler } from '../transition-table-state';

/**
 * QR token abuse protection against the real database (GitHub issue #1107).
 *
 * The emulator rather than a fake Firestore, for the reason every spec in this
 * folder gives: each claim the issue makes is about documents. That a durable
 * counter is shared across instances, that a flood produces one anomaly row
 * rather than a row per request, that a bulk rotation supersedes exactly the
 * codes of one room and leaves the rest of the building printed. A mocked store
 * would assert that the code called `set`, which was never the part in doubt.
 *
 * The rules half - that nobody may write an anomaly and nobody at all may read
 * a counter - is in `src/firestore-rules/__specs__`. The Admin SDK bypasses
 * rules, so it cannot be checked from here.
 *
 * ## Why the limit tests seed a counter instead of looping
 *
 * Reaching the durable token limit honestly is sixty-one resolutions, each of
 * them five document reads and six counter operations, in a spec that would
 * then be measuring the emulator rather than the rule. The counter documents
 * are addressed through this module's own `windowStartOf` and `bucketOf`, so a
 * seeded one is the same document the limiter would have written, and a change
 * to how the name is built fails these tests rather than quietly bypassing
 * them. The counting behaviour itself - that a refused attempt is still
 * counted, that a window rolls - is unit-tested in
 * `shared/utils/__specs__/scan-rate-limit.spec.ts` where it costs nothing.
 */
const PROJECT_ID = 'bite-tribe-emulator-tests';

const OWNER = 'restaurant-owner-uid';
const HOST = 'host-uid';
const OTHER_BUSINESS = 'other-business-uid';

const ALICE = 'guest-alice';

const RESTAURANT = 'owned-restaurant';
const DINING_ROOM = 'dining-room';
const TERRACE = 'terrace';

const TABLE_12 = 'table-12';
const TABLE_5 = 'table-5';
const TERRACE_TABLE = 'table-t1';
const RETIRED_TABLE = 'table-retired';
const MENU = 'menu-1';

/**
 * The fixture tokens, and why each one is a pattern rather than a draw.
 *
 * A real token is 26 characters of Crockford base32 from the system CSPRNG,
 * which is indistinguishable from a leaked credential to any scanner that looks
 * at entropy - and this file would be committing three of them. So each fixture
 * is deliberately, visibly generated by hand: two alphabet runs and a row of
 * nines for the table numbered 99.
 *
 * They still have to be **valid**, because `normalizeScannedToken` refuses
 * anything that is not exactly 26 characters of `TOKEN_ALPHABET` before a
 * single read happens - so a token containing `I`, `L`, `O` or `U` would make
 * every test in this file pass for the wrong reason. Keep them patterned and
 * keep them legal; do not make one look more realistic.
 */
const TOKEN = 'ABCDEFGHJKMNPQRSTVWXYZ0123';
const TOKEN_TABLE_5 = '0123456789ABCDEFGHJKMNPQRS';
const TOKEN_RETIRED = '99999999999999999999999999';

const GUEST_IP = '203.0.113.7';

/** Wednesday 2026-09-16, 12:00 in Berlin. The restaurant is open. */
const LUNCHTIME = new Date('2026-09-16T10:00:00Z');

/** The same Wednesday at 03:00 in Berlin. Nothing is open. */
const MIDDLE_OF_THE_NIGHT = new Date('2026-09-16T01:00:00Z');

/** The restaurant's own position, and two scans measured against it. */
const RESTAURANT_POSITION = { latitude: 52.52, longitude: 13.405 };
const AT_THE_TABLE = {
  latitude: 52.5201,
  longitude: 13.4051,
  accuracyMeters: 20,
};
const ACROSS_THE_CITY = {
  latitude: 52.48,
  longitude: 13.35,
  accuracyMeters: 30,
};

interface Caller {
  uid: string;
  roles: string[];
}

const asOwner: Caller = { uid: OWNER, roles: ['business'] };
const asHost: Caller = { uid: HOST, roles: ['staff'] };
const asOtherBusiness: Caller = { uid: OTHER_BUSINESS, roles: ['business'] };

const businessRequest = (
  caller: Caller,
  data: Record<string, unknown>,
): never =>
  ({
    auth: { uid: caller.uid, token: { roles: caller.roles } },
    data,
  }) as never;

const guestRequest = (
  data: Record<string, unknown>,
  ip = GUEST_IP,
  uid = ALICE,
): never =>
  ({
    auth: {
      uid,
      token: { firebase: { sign_in_provider: 'anonymous' } },
    },
    data,
    rawRequest: { ip },
  }) as never;

/**
 * One resolution from an instance that has never seen this caller.
 *
 * The memory counter is emptied first, which is what a distributed loop looks
 * like from the durable counter's side: thirty requests per instance is under
 * the free limit, so every one of them reaches Firestore. Without the reset
 * these tests would be measuring the in-memory gate.
 */
const scanFromFreshInstance = (
  token = TOKEN,
  now = LUNCHTIME,
  ip = GUEST_IP,
): Promise<TableScanResult> => {
  resetScanRateLimit();

  return resolveTableQrTokenHandler(guestRequest({ token }, ip), now);
};

const start = (
  data: Record<string, unknown> = { token: TOKEN },
  now = LUNCHTIME,
  uid = ALICE,
): Promise<StartTableSessionResult> => {
  resetScanRateLimit();

  return startTableSessionHandler(guestRequest(data, GUEST_IP, uid), now);
};

const rotateBulk = (
  caller: Caller,
  data: Record<string, unknown>,
): Promise<RotateTableQrTokensResult> =>
  rotateTableQrTokensHandler(businessRequest(caller, data));

const dismiss = (
  caller: Caller,
  tableId: string,
  kind: ScanAnomalyKind,
): Promise<DismissScanAnomalyResult> =>
  dismissScanAnomalyHandler(
    businessRequest(caller, { restaurantId: RESTAURANT, tableId, kind }),
  );

const restaurantRef = (): DocumentReference =>
  getFirestore().collection('restaurants').doc(RESTAURANT);

const readAnomaly = async (
  tableId: string,
  kind: ScanAnomalyKind,
): Promise<DocumentData | undefined> =>
  (
    await restaurantRef()
      .collection(SCAN_ANOMALIES_COLLECTION)
      .doc(scanAnomalyId(tableId, kind))
      .get()
  ).data();

const readAnomalies = async (): Promise<DocumentData[]> =>
  (await restaurantRef().collection(SCAN_ANOMALIES_COLLECTION).get()).docs.map(
    (anomaly) => anomaly.data(),
  );

const readToken = async (token: string): Promise<DocumentData | undefined> =>
  (
    await getFirestore().collection(TABLE_TOKENS_COLLECTION).doc(token).get()
  ).data();

const readTable = async (tableId: string): Promise<DocumentData> =>
  (await restaurantRef().collection('tables').doc(tableId).get()).data() ?? {};

/** Puts a counter at the limit, so the next real scan is the one that crosses. */
const fillCounter = (
  dimension: 'token' | 'client' | 'ip',
  value: string,
  count: number,
  now = LUNCHTIME,
): Promise<unknown> => {
  const windowStartedAt = windowStartOf(now.getTime());

  return getFirestore()
    .collection(SCAN_RATE_LIMITS_COLLECTION)
    .doc(`${dimension}_${bucketOf(dimension, value)}_${windowStartedAt}`)
    .set({ dimension, windowStartedAt, count });
};

/** The error code an `HttpsError` carries, or the error itself if it is not one. */
const codeOf = async (call: Promise<unknown>): Promise<string> => {
  try {
    await call;
  } catch (error) {
    return (error as { code?: string }).code ?? String(error);
  }

  return 'no error';
};

const table = (
  label: string,
  roomId = DINING_ROOM,
  enabled = true,
  seats = 4,
): Record<string, unknown> => ({
  label,
  roomId,
  position: { x: 2000, y: 3000 },
  rotation: 0,
  seats,
  enabled,
  shape: 'round',
  diameter: 900,
});

const tokenDocument = (
  tableId: string,
  label: string,
  roomId = DINING_ROOM,
  tableEnabled = true,
): Record<string, unknown> => ({
  restaurantId: RESTAURANT,
  roomId,
  tableId,
  tableLabel: label,
  tableEnabled,
  status: 'active',
  issuedAt: '2026-09-01T09:00:00.000Z',
  issuedAtTimestamp: Date.parse('2026-09-01T09:00:00.000Z'),
});

const seed = async (): Promise<void> => {
  const db = getFirestore();

  await restaurantRef().set({
    name: 'Owned Bistro',
    ownerUserId: OWNER,
    claimStatus: 'claimed',
    menuId: MENU,
    position: RESTAURANT_POSITION,
    openingHours: [
      {
        day: 'wednesday',
        isOpen: true,
        timeRanges: [{ from: '11:30', to: '23:00' }],
      },
    ],
    tableOrdering: { enabled: true, timeZone: 'Europe/Berlin' },
  });

  await Promise.all([
    restaurantRef().collection('tables').doc(TABLE_12).set(table('12')),
    restaurantRef().collection('tables').doc(TABLE_5).set(table('5')),
    restaurantRef()
      .collection('tables')
      .doc(TERRACE_TABLE)
      .set(table('T1', TERRACE)),
    restaurantRef()
      .collection('tables')
      .doc(RETIRED_TABLE)
      .set(table('99', DINING_ROOM, false)),
    restaurantRef()
      .collection('rooms')
      .doc(DINING_ROOM)
      .set({ id: DINING_ROOM, name: 'Main dining room', order: 0 }),
    restaurantRef()
      .collection('rooms')
      .doc(TERRACE)
      .set({ id: TERRACE, name: 'Terrace', order: 1 }),
    db
      .collection('menus')
      .doc(MENU)
      .set({
        id: MENU,
        restaurantId: RESTAURANT,
        categories: [
          {
            id: 'category-pizza',
            title: 'Pizza',
            items: [{ id: 'item-margherita', name: 'Margherita', price: 12 }],
          },
        ],
      }),
    db
      .collection(TABLE_TOKENS_COLLECTION)
      .doc(TOKEN)
      .set(tokenDocument(TABLE_12, '12')),
    db
      .collection(TABLE_TOKENS_COLLECTION)
      .doc(TOKEN_TABLE_5)
      .set(tokenDocument(TABLE_5, '5')),
    db
      .collection(TABLE_TOKENS_COLLECTION)
      .doc(TOKEN_RETIRED)
      .set(tokenDocument(RETIRED_TABLE, '99', DINING_ROOM, false)),
    db
      .collection('restaurantStaff')
      .doc(HOST)
      .set({ userId: HOST, restaurantId: RESTAURANT }),
  ]);
};

const clear = async (): Promise<void> => {
  const db = getFirestore();

  await Promise.all([
    db.recursiveDelete(db.collection('restaurants')),
    db.recursiveDelete(db.collection('restaurantStaff')),
    db.recursiveDelete(db.collection('menus')),
    db.recursiveDelete(db.collection(TABLE_TOKENS_COLLECTION)),
    db.recursiveDelete(db.collection(SCAN_RATE_LIMITS_COLLECTION)),
  ]);
};

describe('QR token abuse protection', () => {
  beforeAll(() => {
    if (!process.env['FIRESTORE_EMULATOR_HOST']) {
      throw new Error(
        'QR abuse protection emulator specs require the Firestore emulator.',
      );
    }

    if (!getApps().length) {
      initializeApp({ projectId: PROJECT_ID });
    }
  });

  beforeEach(async () => {
    resetScanRateLimit();
    await resetDurableScanRateLimit();
    await clear();
    await seed();
  });

  afterAll(async () => {
    await clear();
    await Promise.all(getApps().map((app) => deleteApp(app)));
  });

  describe('the durable rate limit', () => {
    /**
     * The gap issue #1100 left open, closed. Every call here comes from an
     * instance with an empty memory counter, which is what a distributed loop
     * is, and it is refused anyway.
     */
    it('refuses one token past its limit however many instances ask', async () => {
      await fillCounter('token', TOKEN, DURABLE_TOKEN_LIMIT_PER_WINDOW);

      expect(await codeOf(scanFromFreshInstance())).toBe('resource-exhausted');
    });

    it('admits a token that is one short of its limit', async () => {
      await fillCounter('token', TOKEN, DURABLE_TOKEN_LIMIT_PER_WINDOW - 1);

      expect((await scanFromFreshInstance()).ok).toBe(true);
    });

    /**
     * The dimension this issue adds. An attacker holding one throwaway
     * anonymous account per request is bucketed by neither the token count -
     * each request names a different one - nor the client count, and this is
     * what sees it.
     */
    it('refuses one address past its limit across different tokens', async () => {
      await fillCounter('ip', GUEST_IP, DURABLE_IP_LIMIT_PER_WINDOW);

      expect(await codeOf(scanFromFreshInstance(TOKEN_TABLE_5))).toBe(
        'resource-exhausted',
      );
    });

    it('lets another address keep scanning a throttled one', async () => {
      await fillCounter('ip', GUEST_IP, DURABLE_IP_LIMIT_PER_WINDOW);

      expect(
        (await scanFromFreshInstance(TOKEN, LUNCHTIME, '198.51.100.4')).ok,
      ).toBe(true);
    });

    it('starts counting again in the next window', async () => {
      await fillCounter('token', TOKEN, DURABLE_TOKEN_LIMIT_PER_WINDOW);

      const nextWindow = new Date(
        LUNCHTIME.getTime() + DURABLE_RATE_LIMIT_WINDOW_MS,
      );

      expect((await scanFromFreshInstance(TOKEN, nextWindow)).ok).toBe(true);
    });

    /** The acceptance criterion that an address is never written down. */
    it('names the counter after a hash and never after the address', async () => {
      await scanFromFreshInstance();

      const counters = (
        await getFirestore().collection(SCAN_RATE_LIMITS_COLLECTION).get()
      ).docs;

      expect(counters.length).toBeGreaterThan(0);
      expect(counters.map((counter) => counter.id).join(' ')).not.toContain(
        GUEST_IP,
      );
      expect(
        JSON.stringify(counters.map((counter) => counter.data())),
      ).not.toContain(GUEST_IP);
    });
  });

  describe('what a throttled token tells the restaurant', () => {
    /**
     * "Automated resolution attempts are throttled **and observable**". The row
     * is what makes the second half true, and it names the table so the one
     * action that ends it - rotating that code - is obvious.
     */
    it('raises one row against the table whose code is being worked on', async () => {
      await fillCounter('token', TOKEN, DURABLE_TOKEN_LIMIT_PER_WINDOW);
      await codeOf(scanFromFreshInstance());

      expect(await readAnomaly(TABLE_12, 'rateLimited')).toMatchObject({
        restaurantId: RESTAURANT,
        tableId: TABLE_12,
        tableLabel: '12',
        kind: 'rateLimited',
        status: 'open',
        count: 1,
      });
    });

    /**
     * The property that makes writing a row safe on a path the caller controls
     * the frequency of: only the request that crosses the line writes one, and
     * the quiet window absorbs the rest. A flood is one document.
     */
    it('raises one row however many requests are refused after it', async () => {
      await fillCounter('token', TOKEN, DURABLE_TOKEN_LIMIT_PER_WINDOW);

      for (let attempt = 0; attempt < 5; attempt++) {
        await codeOf(scanFromFreshInstance());
      }

      const anomaly = await readAnomaly(TABLE_12, 'rateLimited');

      expect(anomaly).toMatchObject({ count: 1 });
      expect(await readAnomalies()).toHaveLength(1);
    });
  });

  describe('the scans a refusal is worth telling the restaurant about', () => {
    it('raises a row when a retired table keeps being scanned', async () => {
      const result = await scanFromFreshInstance(TOKEN_RETIRED);

      expect(result).toMatchObject({ ok: false, reason: 'tableDisabled' });
      expect(await readAnomaly(RETIRED_TABLE, 'disabledTable')).toMatchObject({
        tableLabel: '99',
        kind: 'disabledTable',
        status: 'open',
        count: 1,
      });
    });

    it('raises a row when a code is scanned in the middle of the night', async () => {
      const result = await scanFromFreshInstance(TOKEN, MIDDLE_OF_THE_NIGHT);

      expect(result).toMatchObject({ ok: false, reason: 'restaurantClosed' });
      expect(await readAnomaly(TABLE_12, 'outsideOpeningHours')).toMatchObject({
        kind: 'outsideOpeningHours',
        count: 1,
      });
    });

    /**
     * The quiet window, from the other side. Two refusals a second apart are
     * one row with one count; the count is raisings and not requests, which the
     * model states and the staff row says.
     */
    it('joins the row that is already up rather than raising a second', async () => {
      await scanFromFreshInstance(TOKEN_RETIRED);
      await scanFromFreshInstance(TOKEN_RETIRED);

      expect(await readAnomaly(RETIRED_TABLE, 'disabledTable')).toMatchObject({
        count: 1,
      });
    });

    it('counts a second burst once the quiet window has passed', async () => {
      await scanFromFreshInstance(TOKEN_RETIRED);
      await scanFromFreshInstance(
        TOKEN_RETIRED,
        new Date(LUNCHTIME.getTime() + 61_000),
      );

      expect(await readAnomaly(RETIRED_TABLE, 'disabledTable')).toMatchObject({
        count: 2,
      });
    });

    /** An ordinary scan says nothing about anybody. */
    it('raises nothing at all for a scan that resolves', async () => {
      expect((await scanFromFreshInstance()).ok).toBe(true);
      expect(await readAnomalies()).toEqual([]);
    });
  });

  describe('the sessions a table is not big enough for', () => {
    const startAs = (uid: string): Promise<StartTableSessionResult> =>
      start({ token: TOKEN }, LUNCHTIME, uid);

    it('raises nothing while the party is explicable by the furniture', async () => {
      for (let guest = 0; guest < MIN_SESSIONS_BEFORE_ANOMALY; guest++) {
        await startAs(`guest-${guest}`);
      }

      expect(await readAnomaly(TABLE_12, 'manySessions')).toBeUndefined();
    });

    it('raises a row once there are more sessions than the table can hold', async () => {
      for (let guest = 0; guest <= MIN_SESSIONS_BEFORE_ANOMALY; guest++) {
        await startAs(`guest-${guest}`);
      }

      expect(await readAnomaly(TABLE_12, 'manySessions')).toMatchObject({
        kind: 'manySessions',
        tableId: TABLE_12,
        sessionCount: MIN_SESSIONS_BEFORE_ANOMALY + 1,
      });
    });

    /**
     * A phone that reloads the confirmation screen has not added a person to
     * the table, so a resumed session is not counted a second time and cannot
     * be what tips a table over the threshold.
     */
    it('does not re-evaluate a guest who is only resuming', async () => {
      for (let guest = 0; guest < MIN_SESSIONS_BEFORE_ANOMALY; guest++) {
        await startAs(`guest-${guest}`);
      }

      await startAs('guest-0');

      expect(await readAnomaly(TABLE_12, 'manySessions')).toBeUndefined();
    });
  });

  describe('when the reporting itself cannot run', () => {
    /**
     * The query `liveSessionsAt` makes needs a composite index, indexes in this
     * repository **deploy by hand**, and the emulator does not enforce them - so
     * the day the functions deploy and the index deploy has not run is a day
     * this call fails for a reason that has nothing to do with the guest. Before
     * the guard, that would have committed the session and then answered with
     * `FAILED_PRECONDITION`: a session that exists, reported as a failure,
     * because a row on a staff screen could not be counted.
     *
     * Forced rather than waited for, by rejecting the one `Query` this handler
     * makes - `resolveScan` reads documents and `getAll`, and the transaction
     * uses its own `get`, so a single rejection lands exactly here.
     */
    it('still starts the session when the count cannot be read', async () => {
      const queryPrototype = Object.getPrototypeOf(
        restaurantRef()
          .collection('tableSessions')
          .where('tableId', '==', TABLE_12),
      );
      const get = jest
        .spyOn(queryPrototype, 'get')
        .mockRejectedValueOnce(new Error('9 FAILED_PRECONDITION: no index'));

      try {
        const result = await start();

        expect(get).toHaveBeenCalled();
        expect(result).toMatchObject({ ok: true, status: 'pending' });
        expect(
          (
            await restaurantRef()
              .collection('tableSessions')
              .doc(tableSessionId(TABLE_12, ALICE))
              .get()
          ).data(),
        ).toMatchObject({ status: 'pending' });
      } finally {
        get.mockRestore();
      }
    });
  });

  describe('the coarse position, when the guest shares one', () => {
    /**
     * The acceptance criterion in full: a guest who declines scans, sits down
     * and orders exactly as one who allows it. Nothing here branches on the
     * position except the row it may raise.
     */
    it('starts the same session whether a position is sent or not', async () => {
      const without = await start({ token: TOKEN });
      const withPosition = await start(
        { token: TOKEN_TABLE_5, position: ACROSS_THE_CITY },
        LUNCHTIME,
        'guest-bob',
      );

      expect(without).toMatchObject({ ok: true, status: 'pending' });
      expect(withPosition).toMatchObject({ ok: true, status: 'pending' });
    });

    it('raises a row for a scan from across the city', async () => {
      await start({ token: TOKEN, position: ACROSS_THE_CITY });

      const anomaly = await readAnomaly(TABLE_12, 'distantScan');

      expect(anomaly).toMatchObject({ kind: 'distantScan' });
      expect(anomaly?.['distanceMeters']).toBeGreaterThan(500);
    });

    it('raises nothing for a scan at the table', async () => {
      await start({ token: TOKEN, position: AT_THE_TABLE });

      expect(await readAnomaly(TABLE_12, 'distantScan')).toBeUndefined();
    });

    /**
     * A fix too coarse to support the claim makes none. A device reporting five
     * kilometres of uncertainty cannot say anybody is more than five hundred
     * metres away.
     */
    it('raises nothing when the fix is vaguer than the distance', async () => {
      await start({
        token: TOKEN,
        position: { ...ACROSS_THE_CITY, accuracyMeters: 50_000 },
      });

      expect(await readAnomaly(TABLE_12, 'distantScan')).toBeUndefined();
    });

    it('ignores a malformed position exactly as it ignores an absent one', async () => {
      const result = await start({
        token: TOKEN,
        position: { latitude: 'here', longitude: null },
      });

      expect(result).toMatchObject({ ok: true, status: 'pending' });
      expect(await readAnomalies()).toEqual([]);
    });

    /** The coordinates are compared and discarded; only a distance survives. */
    it('stores no coordinates anywhere', async () => {
      await start({ token: TOKEN, position: ACROSS_THE_CITY });

      const session = (
        await restaurantRef()
          .collection('tableSessions')
          .doc(tableSessionId(TABLE_12, ALICE))
          .get()
      ).data();

      expect(JSON.stringify(session)).not.toContain('52.48');
      expect(JSON.stringify(await readAnomalies())).not.toContain('52.48');
    });
  });

  describe('dismissing a row', () => {
    const raise = async (): Promise<void> => {
      await scanFromFreshInstance(TOKEN_RETIRED);
    };

    it('marks it read and names who read it', async () => {
      await raise();

      const result = await dismiss(asHost, RETIRED_TABLE, 'disabledTable');

      expect(result).toMatchObject({
        status: 'dismissed',
        dismissedByUserId: HOST,
        changed: true,
      });
      expect(await readAnomaly(RETIRED_TABLE, 'disabledTable')).toMatchObject({
        status: 'dismissed',
      });
    });

    it('answers a second press with what is stored rather than a conflict', async () => {
      await raise();
      await dismiss(asHost, RETIRED_TABLE, 'disabledTable');

      expect(
        await dismiss(asOwner, RETIRED_TABLE, 'disabledTable'),
      ).toMatchObject({ dismissedByUserId: HOST, changed: false });
    });

    /**
     * A dismissal says somebody read the row, not that the table is exempt. The
     * document keeps its name and its history, so a kind that starts again
     * comes back as the same row with its count intact.
     */
    it('re-opens when the same kind is raised again, keeping its history', async () => {
      await raise();
      await dismiss(asHost, RETIRED_TABLE, 'disabledTable');
      await scanFromFreshInstance(
        TOKEN_RETIRED,
        new Date(LUNCHTIME.getTime() + 61_000),
      );

      expect(await readAnomaly(RETIRED_TABLE, 'disabledTable')).toMatchObject({
        status: 'open',
        count: 2,
      });
    });

    it('refuses an account that does not work at the restaurant', async () => {
      await raise();

      expect(
        await codeOf(dismiss(asOtherBusiness, RETIRED_TABLE, 'disabledTable')),
      ).toBe('permission-denied');
    });

    it('refuses a kind it does not know', async () => {
      expect(
        await codeOf(
          dismissScanAnomalyHandler(
            businessRequest(asHost, {
              restaurantId: RESTAURANT,
              tableId: TABLE_12,
              kind: 'somethingElse',
            }),
          ),
        ),
      ).toBe('invalid-argument');
    });
  });

  describe('rotating a room', () => {
    const issuedTokenOf = async (tableId: string): Promise<string> =>
      String((await readTable(tableId))['qrTokenId'] ?? '');

    beforeEach(async () => {
      await Promise.all([
        restaurantRef()
          .collection('tables')
          .doc(TABLE_12)
          .update({ qrTokenId: TOKEN }),
        restaurantRef()
          .collection('tables')
          .doc(TABLE_5)
          .update({ qrTokenId: TOKEN_TABLE_5 }),
      ]);
    });

    /**
     * The acceptance criterion "a room's codes can be rotated in one action".
     * Every table of the room gets a new code and the old ones are superseded
     * rather than deleted, so a guest holding the old sheet is told to look at
     * the table again rather than told nothing.
     */
    it('replaces every code of the room in one call', async () => {
      const result = await rotateBulk(asOwner, {
        restaurantId: RESTAURANT,
        roomId: DINING_ROOM,
      });

      expect(result.tokens).toHaveLength(2);
      expect(result.roomId).toBe(DINING_ROOM);

      for (const rotated of result.tokens) {
        expect(rotated.status).toBe('rotated');
        expect(await issuedTokenOf(rotated.tableId)).toBe(rotated.token);
      }

      expect(await readToken(TOKEN)).toMatchObject({
        status: 'superseded',
        supersededBy: await issuedTokenOf(TABLE_12),
      });
    });

    /** Without reprinting the whole building: the terrace keeps its sticker. */
    it('leaves the other rooms printed', async () => {
      await rotateBulk(asOwner, {
        restaurantId: RESTAURANT,
        roomId: DINING_ROOM,
      });

      expect(await issuedTokenOf(TERRACE_TABLE)).toBe('');
    });

    it('skips a table that is out of service rather than refusing the room', async () => {
      const result = await rotateBulk(asOwner, {
        restaurantId: RESTAURANT,
        roomId: DINING_ROOM,
      });

      expect(result.skippedTableIds).toContain(RETIRED_TABLE);
    });

    it('rotates a named set of tables across rooms', async () => {
      const result = await rotateBulk(asOwner, {
        restaurantId: RESTAURANT,
        tableIds: [TABLE_12, TERRACE_TABLE],
      });

      expect(result.tokens.map(({ tableId }) => tableId).sort()).toEqual(
        [TABLE_12, TERRACE_TABLE].sort(),
      );
    });

    /**
     * "Rotate everything" is not reachable by leaving an argument out. It is
     * the one action here that invalidates every sticker in the building, and a
     * caller that meant a room and sent an empty object would have got it.
     */
    it('refuses a rotation that names no scope', async () => {
      expect(
        await codeOf(rotateBulk(asOwner, { restaurantId: RESTAURANT })),
      ).toBe('invalid-argument');
    });

    it('refuses an account that does not hold the restaurant', async () => {
      expect(
        await codeOf(
          rotateBulk(asOtherBusiness, {
            restaurantId: RESTAURANT,
            roomId: DINING_ROOM,
          }),
        ),
      ).toBe('permission-denied');
    });

    /**
     * A rotated code stops working immediately, which is the epic's own success
     * criterion and the reason any of this is one action rather than a support
     * conversation.
     */
    it('stops the rotated code resolving', async () => {
      await rotateBulk(asOwner, {
        restaurantId: RESTAURANT,
        roomId: DINING_ROOM,
      });

      expect(await scanFromFreshInstance(TOKEN)).toMatchObject({
        ok: false,
        reason: 'tokenSuperseded',
        nextStep: 'rescanCode',
      });
    });
  });

  describe('a pending session, which is not an anomaly at all', () => {
    /**
     * `RD-TS-1`'s signal, as a document staff can list. Nothing about it is
     * suspicious - it is a guest who scanned while waiting to be seated - so it
     * raises no row, and the business app draws it from the sessions rather
     * than from the anomalies.
     */
    it('is a session staff can read and not a row on the anomaly list', async () => {
      await start();

      const pending = (
        await restaurantRef()
          .collection('tableSessions')
          .where('status', '==', 'pending')
          .get()
      ).docs.map((session) => session.data());

      expect(pending).toHaveLength(1);
      expect(pending[0]).toMatchObject({
        tableId: TABLE_12,
        status: 'pending',
      });
      expect(await readAnomalies()).toEqual([]);
    });

    /** Seating the table is the confirmation, and it ends the waiting. */
    it('stops being pending once staff seat the table', async () => {
      await start();

      await transitionTableStateHandler(
        businessRequest(asHost, {
          restaurantId: RESTAURANT,
          tableId: TABLE_12,
          status: 'occupied',
          expectedStatus: 'available',
        }),
      );

      const pending = await restaurantRef()
        .collection('tableSessions')
        .where('status', '==', 'pending')
        .get();

      expect(pending.empty).toBe(true);
    });
  });
});
