name: "Create pull request"
description: "Creates a pull request"

inputs:
  branch_name:
    description: "Name of the branch to create"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      shell: bash
      run: |
        gh pr create --base develop --head ${{ inputs.branch_name }} --title "chore: update loki references" --body ""
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
