name: "Push branch"
description: "Pushes a branch"

inputs:
  branch_name:
    description: "Name of the branch to create"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Push branch
      shell: bash
      run: |
        git push -u origin ${{ inputs.branch_name }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
