export const PATH = {
  START: 'start',
  NEW_BITE: 'new-bite',
  MY_BITES: 'my-bites',
  BITES: 'bites',
  BITE: 'bite',
  HOME: 'home',
  EDIT_PROFILE: 'edit-profile',
  PROFILE: 'profile',
  MY_PROFILE: 'my-profile',
  ABOUT: 'about',
  FOLLOWERS: 'followers',
  MY_BUCKETLISTS: 'my-bucketlists',
  RESTAURANT: 'restaurant',
  PLACE: 'place',
  MENU: 'menu',
  PRIVACY_POLICY: 'privacy',
  ACCOUNT_DELETION: 'account-deletion',
  MARKET_PLACE: 'market-place',
  BITE_TRAIL: 'bite-trail',
};
