name: "Restore Cache"
description: "Restores cache if given"
runs:
  using: "composite"
  steps:
    - name: Cache restore
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
