name: Deploy Bite Tribe Storybook

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  deploy-bite-tribe-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup action
        uses: ./.github/actions/setup

      - name: Build Bite Tribe Storybook
        run: npm run build:storybook

      - name: Bite Tribe Storybook Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BITE_TRIBE }}'
          projectId: bite-tribe
          target: bite-tribe-storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Bite Tribe Storybook Publish to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BITE_TRIBE }}'
          channelId: live
          projectId: bite-tribe
          target: bite-tribe-storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
