name: Loki References Update

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  BRANCH_NAME: update-loki-references

jobs:
  update-loki-references:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Create branch
          uses: ./.github/actions/create-branch
          with:
            branch_name: ${{ env.BRANCH_NAME }}

        - name: Setup action
          uses: ./.github/actions/setup

        - name: Build Storybook
          shell: bash
          run: npm run build:storybook

        - name: Generate Loki References
          shell: bash
          run: |
            npm run loki:update

            HAS_CHANGES=$( [[ -n "$(git status --porcelain)" ]] && echo "true" || echo "false" )

            if [ "$HAS_CHANGES" = "true" ]; then
              git add .
              git commit -m "chore: update loki references"

              echo "HAS_CHANGES=true" >> $GITHUB_ENV
            else
              echo "No changes to commit"
              echo "HAS_CHANGES=false" >> $GITHUB_ENV
            fi

        - name: Push branch
          if: env.HAS_CHANGES == 'true'
          uses: ./.github/actions/push-branch
          with:
            branch_name: ${{ env.BRANCH_NAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create pull request
          if: env.HAS_CHANGES == 'true'
          uses: ./.github/actions/create-pull-request
          with:
            branch_name: ${{ env.BRANCH_NAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
