name: Loki References Update

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  BRANCH_NAME: update-loki-references

jobs:
  update-loki-references:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Create branch
          uses: ./.github/actions/create-branch
          with:
            branch_name: ${{ env.BRANCH_NAME }}

        - name: Setup action
          uses: ./.github/actions/setup

        - name: Generate Loki References
          shell: bash
          run: |
            npm run nx -- run-many --target=update-loki --all

            git add .
            git commit --allow-empty -m "chore: update loki references"

        - name: Push branch
          uses: ./.github/actions/push-branch
          with:
            branch_name: ${{ env.BRANCH_NAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create pull request
          uses: ./.github/actions/create-pull-request
          with:
            branch_name: ${{ env.BRANCH_NAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
