name: Travellers Apps CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  NX_BRANCH: ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.ref_name}} - ${{github.ref}}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - run: npm ci
      - run: npm run nx -- affected --target=build
      - run: npm run nx -- affected --target=build-storybook

      - name: Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Publish App to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Storybook Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Publish Storybook to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

