name: Travellers Apps CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Cache Nx
        id: nx-cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('package-lock') }}-${{ github.sha }}
      - run: |
          echo "CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - run: npm ci
      - run: npm run nx -- affected --target=build
        if: steps.cache.outputs.cache-hit == 'true'
      - run: npm run nx -- build prices
        if: steps.cache.outputs.cache-hit == 'false'
      # - run: npm test
      #   continue-on-error: true
      - name: Preview of Pull Request
        continue-on-error: true
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Publish App to Firebase
        continue-on-error: true
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Cache Nx
        id: nxcache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-storybook-${{ hashFiles('package.lock') }}-${{ github.sha }}
          restore-keys: cache-nx-storybook-${{ hashFiles('package.lock') }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - run: npm ci
      - run: npm run nx -- affected --target=build-storybook
        if: steps.nxcache.outputs.cache-hit == 'true'
      - run: npm run nx -- build-storybook prices
        if: steps.nxcache.outputs.cache-hit == 'false'
      # - run: npm test
      #   continue-on-error: true
      - name: Storybook Preview of Pull Request
        continue-on-error: true
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Publish Storybook to Firebase
        continue-on-error: true
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
