name: Travellers Apps CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: NPM Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run nx -- run-many --target=test --exclude=kosaml --coverage --coverageReporters=cobertura

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage # optional
          files: ./coverage/apps/prices/cobertura-coverage.xml,
            libs/utils-common/cobertura-coverage.xml,
            libs/prices/add-item/feature/cobertura-coverage.xml,
            libs/prices/auth/feature/cobertura-coverage.xml,
            libs/prices/card/feature/cobertura-coverage.xml,
            libs/prices/firestore/feature/cobertura-coverage.xml,
            libs/prices/geoapify/feature/cobertura-coverage.xml,
            libs/prices/home/feature/cobertura-coverage.xml,
            libs/prices/page/feature/cobertura-coverage.xml,
            libs/prices/password-validator/feature/cobertura-coverage.xml,
            libs/prices/registration/feature/cobertura-coverage.xml,
            libs/prices/shell/feature/cobertura-coverage.xml,
            libs/prices/store/feature/cobertura-coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)

      - name: Run Linter
        run: npm run nx -- run-many --target=lint

      - name: Build Prices App
        run: npm run nx -- build prices
        env:
          NX_APP_API_KEY: ${{ secrets.NX_APP_API_KEY }}
          NX_APP_AUTH_DOMAIN: ${{ secrets.NX_APP_AUTH_DOMAIN }}
          NX_APP_PROJECT_ID: ${{ secrets.NX_APP_PROJECT_ID }}
          NX_APP_STORAGE_BUCKET: ${{ secrets.NX_APP_STORAGE_BUCKET }}
          NX_APP_MESSAGING_SENDER_ID: ${{ secrets.NX_APP_MESSAGING_SENDER_ID }}
          NX_APP_GEOAPIFY_API_KEY: ${{ secrets.NX_APP_GEOAPIFY_API_KEY }}

      - name: Capacitor Sync
        run: npm run cap:sync

      - name: Prices Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Prices Publish to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci

      - run: npm run nx -- build-storybook prices --configuration=ci

      - run: npm run nx -- loki prices

      - name: Storybook Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Storybook Publish to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Run E2E Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          install: true
          command: |
            npm run nx -- e2e prices-e2e --configurations=production
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
          NX_APP_API_KEY: ${{ secrets.NX_APP_API_KEY }}

