name: Travellers Apps CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      nx_verbose_logging:
        description: 'NX Verbose Logging'
        required: false
        default: 'false'
        type: boolean

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: ${{ github.event.inputs.nx_verbose_logging }}
  NX_BASE: develop

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup action
        uses: ./.github/actions/setup

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: "Setup env"
        uses: ./.github/actions/setup-env-for-affected

      - name: Run Linter
        run: npm run nx -- affected -t lint

  stylelint:
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: "Setup env"
        uses: ./.github/actions/setup-env-for-affected

      - name: Run Stylelint
        run: npm run nx -- affected -t stylelint

  tests:
    runs-on: ubuntu-latest
    needs:
      - stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: "Setup env"
        uses: ./.github/actions/setup-env-for-affected

      - name: Run Unit Tests
        run: npm run nx -- affected -t test --coverage --coverageReporters=cobertura

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)

  #build-storybooks:
  #  runs-on: ubuntu-latest
  #  needs:
  #    - tests
  #
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0 # Fetch all history for all branches and tags
  #
  #    - name: "Restore Cache"
  #      uses: ./.github/actions/restore-cache
  #
  #    - name: "Setup env"
  #      uses: ./.github/actions/setup-env-for-affected
  #
  #    - run: npm run nx -- affected -t build-storybook --configuration=ci
  #
  #    - name: Cache Storybook Builds
  #      uses: actions/cache@v4
  #      with:
  #        path: dist/storybook
  #        key: storybooks-${{ hashFiles('**/**/*.stories.*') }}

  #loki:
  #  runs-on: ubuntu-latest
  #  continue-on-error: true
  #  needs:
  #    - build-storybooks
  #
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0 # Fetch all history for all branches and tags
  #
  #    - name: "Restore Cache"
  #      uses: ./.github/actions/restore-cache
  #
  #    - name: "Setup env"
  #      uses: ./.github/actions/setup-env-for-affected
  #
  #    - uses: actions/cache/restore@v4
  #      with:
  #        path: dist/storybook/xxx
  #        key: storybooks-${{ hashFiles('**/**/*.stories.*') }}
  #
  #    - run: npm run nx -- affected -t test-loki
  #
  #    - name: Upload xxx Diffs
  #      uses: actions/upload-artifact@v4
  #      if: failure()
  #      with:
  #        name: loki-diffs
  #        path: apps/**/.loki/difference

# Bite Tribe

  bite-tribe-build:
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: Build Bite Tribe App
        run: npm run nx -- build bite-tribe

  # Bite Tribe Business

  bite-tribe-business-build:
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: Build Bite Tribe App
        run: npm run nx -- build bite-tribe-business

# CV

  cv-build:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: "Restore Cache"
        uses: ./.github/actions/restore-cache

      - name: Build CV App
        run: npm run nx -- build cv

      - name: Cache CV Build
        uses: actions/cache@v4
        with:
          path: dist/apps/cv/browser
          key: cv-build-${{ hashFiles('package-lock.json') }}
