name: Travellers Apps CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 18.x
          cache: 'npm'

      - name: NPM Dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

#Common

  common-lint:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Linter
        run: npm run nx -- run-many --target=lint --projects=\"common*\"

#Utils

  utils-lint:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Linter
        run: npm run nx -- run-many --target=lint --projects=\"utils*\"

#Prices

  prices-stylelint:
    runs-on: ubuntu-latest
    needs:
      - common-lint
      - utils-lint
      - prices-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Stylelint
        run: npm run nx -- run-many --target=stylelint --projects=\"prices*\"

  prices-lint:
    runs-on: ubuntu-latest
    needs:
      - prices-stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Linter
        run: npm run nx -- run-many --target=lint --projects=\"prices*\"

  prices-tests:
    runs-on: ubuntu-latest
    needs:
      - prices-stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Unit Tests
        run: npm run nx -- run-many --target=test --projects="prices*"  --coverage --coverageReporters=cobertura

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage # optional
          files: ./coverage/apps/prices/cobertura-coverage.xml,
            libs/prices/add-item/feature/cobertura-coverage.xml,
            libs/prices/auth/feature/cobertura-coverage.xml,
            libs/prices/card/feature/cobertura-coverage.xml,
            libs/prices/firestore/feature/cobertura-coverage.xml,
            libs/prices/geoapify/feature/cobertura-coverage.xml,
            libs/prices/home/feature/cobertura-coverage.xml,
            libs/prices/page/feature/cobertura-coverage.xml,
            libs/prices/password-validator/feature/cobertura-coverage.xml,
            libs/prices/registration/feature/cobertura-coverage.xml,
            libs/prices/shell/feature/cobertura-coverage.xml,
            libs/prices/store/feature/cobertura-coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)

  prices-build-storybook:
    runs-on: ubuntu-latest
    needs:
      - prices-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm run nx -- build-storybook prices --configuration=ci

      - name: Cache Storybook Build
        uses: actions/cache@v3
        with:
          path: dist/storybook/prices
          key: prices-storybook-${{ hashFiles('**/prices/**/*.stories.*') }}

  prices-loki:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - prices-build-storybook

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache/restore@v3
        with:
          path: dist/storybook/prices
          key: prices-storybook-${{ hashFiles('**/prices/**/*.stories.*') }}

      - run: npm run nx -- loki prices

      - name: Upload Prices Diffs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: prices-loki-diffs
          path: apps/prices/.loki/difference

  prices-deploy-storybook:
    runs-on: ubuntu-latest
    needs:
      - prices-loki

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache/restore@v3
        with:
          path: dist/storybook/prices
          key: prices-storybook-${{ hashFiles('**/prices/**/*.stories.*') }}

      - name: Storybook Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Storybook Publish to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: storybook
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  prices-e2e-test:
    runs-on: ubuntu-latest
    needs:
      - prices-loki

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Run E2E Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          install: true
          command: |
            npm run nx -- e2e prices-e2e --configurations=production
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
          NX_APP_API_KEY: ${{ secrets.NX_APP_API_KEY }}

  prices-build:
    runs-on: ubuntu-latest
    needs:
      - prices-e2e-test
      - common-lint
      - utils-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build Prices App
        run: npm run nx -- build prices
        env:
          NX_APP_API_KEY: ${{ secrets.NX_APP_API_KEY }}
          NX_APP_AUTH_DOMAIN: ${{ secrets.NX_APP_AUTH_DOMAIN }}
          NX_APP_PROJECT_ID: ${{ secrets.NX_APP_PROJECT_ID }}
          NX_APP_STORAGE_BUCKET: ${{ secrets.NX_APP_STORAGE_BUCKET }}
          NX_APP_MESSAGING_SENDER_ID: ${{ secrets.NX_APP_MESSAGING_SENDER_ID }}
          NX_APP_GEOAPIFY_API_KEY: ${{ secrets.NX_APP_GEOAPIFY_API_KEY }}

      - name: Cache Prices Build
        uses: actions/cache@v3
        with:
          path: dist/apps/prices
          key: prices-build-${{ hashFiles('package-lock.json') }}

  prices-cap-sync:
    runs-on: ubuntu-latest
    needs:
      - prices-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache/restore@v3
        with:
          path: dist/apps/prices
          key: prices-build-${{ hashFiles('package-lock.json') }}

      - name: Capacitor Sync
        run: npm run cap:sync

  prices-deploy:
    runs-on: ubuntu-latest
    needs:
      - prices-cap-sync

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache/restore@v3
        with:
          path: dist/apps/prices
          key: prices-build-${{ hashFiles('package-lock.json') }}

      - name: Prices Preview of Pull Request
        if: github.event.pull_request.base.ref == 'develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Prices Publish to Firebase
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRICES_BEC89 }}'
          channelId: live
          projectId: prices-bec89
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

# KOSAML

  kosaml-stylelint:
    runs-on: ubuntu-latest
    needs:
      - common-lint
      - utils-lint
      - kosaml-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Stylelint
        run: npm run nx -- run-many --target=stylelint --projects=\"kosaml*\"

  kosaml-lint:
    runs-on: ubuntu-latest
    needs:
      - kosaml-stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Linter
        run: npm run nx -- run-many --target=lint --projects="kosaml*"

  kosaml-tests:
    runs-on: ubuntu-latest
    needs:
      - kosaml-stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run Unit Tests
        run: npm run nx -- run-many --target=test --projects="kosaml*"  --coverage --coverageReporters=cobertura

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage # optional
          files: ./coverage/apps/kosaml/cobertura-coverage.xml,
            libs/kosaml/auth/feature/cobertura-coverage.xml,
            libs/kosaml/card/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/base/scenario/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/base/use-case/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/concrete-use-case/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/essential-use-case/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/task-object/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/task-scenario/feature/cobertura-coverage.xml,
            libs/kosaml/conceptual-design/use-scenario/feature/cobertura-coverage.xml,
            libs/kosaml/model/feature/cobertura-coverage.xml,
            libs/kosaml/page/feature/cobertura-coverage.xml,
            libs/kosaml/shell/feature/cobertura-coverage.xml,
            libs/kosaml/site/feature/cobertura-coverage.xml,
            libs/kosaml/store/feature/cobertura-coverage.xml,
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)

  kosaml-build-storybook:
    runs-on: ubuntu-latest
    needs:
      - kosaml-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm run nx -- build-storybook kosaml --configuration=ci

      - name: Cache Storybook Build
        uses: actions/cache@v3
        with:
          path: dist/storybook/kosaml
          key: kosaml-storybook-${{ hashFiles('**/kosaml/**/*.stories.*') }}

  kosaml-loki:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - kosaml-build-storybook

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache/restore@v3
        with:
          path: dist/storybook/kosaml
          key: kosaml-storybook-${{ hashFiles('**/kosaml/**/*.stories.*') }}

      - run: npm run nx -- loki kosaml

      - name: Upload Loki Diffs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: kosaml-loki-diffs
          path: apps/kosaml/.loki/difference

  kosaml-build:
    runs-on: ubuntu-latest
    needs:
      - kosaml-loki
      - common-lint
      - utils-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build Prices App
        run: npm run nx -- build kosaml



